- name: Déployer l'app front-end sur le VPS
  hosts: vps
  become: yes
  vars:
    app_local_build_dir: ./dist
    app_remote_dir: /var/www/skillsconnect
  tasks:
    - name: S'assurer que le dossier cible existe
      file:
        path: "{{ app_remote_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copier les fichiers buildés sur le VPS
      synchronize:
        src: "{{ app_local_build_dir }}/"
        dest: "{{ app_remote_dir }}/"
        delete: yes
        recursive: yes

    - name: S'assurer que les droits sont corrects
      file:
        path: "{{ app_remote_dir }}"
        owner: www-data
        group: www-data
        recurse: yes